CREATE TABLE bus_route
(
    BUS_ROUTE_ID NUMBER(3,0) NOT NULL ENABLE,
	BUS_ROUTE_RANGE NUMBER(10,0),
	BUS_ROUTE_STOP_NUMBER NUMBER(3,0),
    CONSTRAINT "BUS_ROUTE_PK" PRIMARY KEY ("BUS_ROUTE_ID")
);
CREATE TABLE driver
(
    DRIVER_ID NUMBER(6,0) NOT NULL ENABLE,
	DRIVER_NAME NVARCHAR2(50),
	DRIVER_ADDRESS NVARCHAR2(50),
	DRIVER_PHONE NVARCHAR2(15),
	DRIVER_LEVEL NVARCHAR2(1),
	 CONSTRAINT "DRIVER_PK" PRIMARY KEY ("DRIVER_ID")
);
CREATE TABLE roster
(
    DRIVER_ID NUMBER(5,0),
    BUS_ROUTE_ID NUMBER(3,0),
	ROUTE_QUANTITY NUMBER(4,0),
    CONSTRAINT "FK_DRIVER" FOREIGN KEY ("DRIVER_ID")
    REFERENCES "DRIVER" ("DRIVER_ID") ENABLE,
    CONSTRAINT "FK_BUS_ROUTE" FOREIGN KEY ("BUS_ROUTE_ID")
    REFERENCES "BUS_ROUTE" ("BUS_ROUTE_ID") ENABLE
)

INSERT INTO bus_route VALUES(100,300,10);
INSERT INTO bus_route VALUES(101,250,8);
INSERT INTO driver VALUES(10000, 'chinh', 'hai duong', '0968476166', 'A');
INSERT INTO roster VALUES(10000,100,5);
INSERT INTO roster VALUES(10000,101,5);